### ISSUE TITLE
Construcción de la ventana1 y la primera parte

### ISSUE THREAD

**Issue by AlliSerna23231** [AlliSerna23231/Clase9#1]
Construir la ventana1  y hacer el formulario para ingresar la información del cliente

**Comment by SernaAllis** [comment]
Saludos yo me encargo de eso

**Comment by SernaAllis** [comment]
Listo trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1.py el formulario del registro del usuario

**Comment by AlliSerna23231** [comment]
Ok.
