### ISSUE TITLE
Programar el botón para buscar las preguntas y recuperar contraseña

### ISSUE THREAD

**Issue by AlliSerna23231** [AlliSerna23231/Clase9#6]
Validar que se haya ingresado el documento del usuario al cual se le va a buscar la contraseña.
Validar que el documento sea un dato de tipo numérico.
Crear la clase del usuario con sus 11 propiedades
Solo considerar una contraseña 
Buscar las preguntas para recuperar la contraseña

**Comment by SernaAllis** [comment]
Listo, ya mismo.

**Comment by AlliSerna23231** [comment]
Ok, quedo pendiente de su primer push y pull request.
